### ISSUE TITLE
filter docker journald logging driver messages

### ISSUE THREAD

**Issue by asychev** [mheese/journalbeat#111]
At the moment I'm exploring the possibility of using docker journald logging driver (https://docs.docker.com/engine/admin/logging/journald/) together with journalbeat to send docker container logs to graylog2 beats input. I need to filter messages by CONTAINER_NAME or CONTAINER_TAG (see link, "Retrieve log messages with journalctl"). As far as I understand, now it is not feasible with the use of "units" config parameter in journalbeat.yml?

**Comment by nicorevin** [comment]
yes unfortunately. "units" is the equivalent of `journalctl -u` which is different from `journacltl CONTAINER_NAME`

**Comment by asychev** [comment]
Is it technically possible to implement this?

**Comment by hookenz** [comment]
Yes.   It's possible.  That might be useful.   I'll take a look.

**Comment by mheese** [comment]
yes, it's not difficult to do ... the better question is more "what is the right way to do it".

The latest implementation for units was improved (thanks to @hookenz ) to adapt the same behaviour that `journalctl -u` has. I think that normally this is how people are filtering logs when viewing them with `journalctl`, however, the more general filtering technique by `journalctl` is the filtering in the arguments ... e.g. we should probably add a more general, generic `filter` array to the config, that allows the same pattern that `journalctl CONTAINER_NAME=container_name` would do.

**Comment by mheese** [comment]
This is a similar request to #104 . Let's see if we can find a clear and general way to implement this.

**Comment by hookenz** [comment]
@asychev Would processors work for you?

See:  [processors](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-processors.html#processors)

This is part of the beats library that journalbeat uses.  I'm already using it to convert message field containing JSON to fields for example and filtering out fields I'm not interested in.

e.g.

````
processors:
 - drop_event:
     when:
        not:
          equals:
            container_name: "yourcontainername"
````
Or
````
processors:
 - drop_event:
     when:
        not:
          regexp:
            container_name: "name*"
````
etc...

You can also combine it with units 

Or simply drop all units that don't have the "container_name" field.
