### ISSUE TITLE
Exclude units

### ISSUE THREAD

**Issue by c4milo** [mheese/journalbeat#112]
Is there a way to exclude units? I would like to forward all units logs except journalbeat's own log.

**Comment by hookenz** [comment]
Use the `units= [ unit names... ]` in `journalbeat.yml` file.  
That will white list only the units you are interested in.  You can now also use wild cards in there.

Or, since journalbeat uses the beats library this may work as well.

````
processors:
 - drop_event:
     when:
        equals:
          unit.name: "journalbeat.service"
````
