### ISSUE TITLE
Add matching on other Journal Fields

### ISSUE THREAD

**Issue by maddisondavid** [mheese/journalbeat#119]
Currently JournalBeat only matches on units, however we use JournalBeat within DCOS and really need to locate and match journal entries on fields other than unit.

The idea is that users would specify custom patterns for these extra use cases, i.e, the following would match all entries that had a `GROUP` field with a value of `platform`

```
journalbeat:
  clean_field_names: true

  match_patterns:
    - GROUP=platform
```

**Comment by hookenz** [comment]
In fact it's already supported.  Use processors which come with the beat library.  
It should work something like the following

````
processors:
 - drop_event:
     when:
        not:
          equals:
            group: "platform"
````

Or

````
processors:
 - drop_event:
     when:
        not:
          regexp: 
              group: "platform*"
````


Note: journalbeat would have already made the field lowercase.
See: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-processors.html#condition-regexp
