### ISSUE TITLE
Looking for the best way to capture all data

### ISSUE THREAD

**Issue by freakynl** [mheese/journalbeat#122]
Hi there,

after setting up journalbeat for the first time we noticed that it nicely shipped logs with the below config:

```
journalbeat:
  seek_position: cursor 
  cursor_seek_fallback: head 
  write_cursor_state: true
  cursor_state_file: .journalbeat-cursor-state
  cursor_flush_period: 60s
  pending_queue.file: .journalbeat-pending-queue
  pending_queue.flush_period: 60s

name: journalbeat

output.logstash:
  enabled: true
  hosts: ["10.234.234.18:5044"]
  compression_level: 9

logging.level: debug 
logging.to_files: false 

```

Unfortunately we came to the conclusion that this didn't include all logs. When comparing with a simple 'journalctl -b' we noticed the first half (rough estimated) was more or less missing. Most notably the first parts of the boot process / kernel output.

Have now configured

`
queue_size: 50000
`

And noticed we are getting everything now (deleted the cursor state file), or at least much more (it includes a whole bunch of previous boots as well now).

There's several things we'd like to accomplish:

* Have journalbeat send *everything* from the current boot. As it runs in RAM we have deleted /var/log/journal from the initramfs filesystem, journald recreates it on startup. As such I don't have much concerns about it shipping data from previous boots, as there is none, but perhaps others do :).
* Have some form of compression to ship (using gzip level 9 now - should be fine)
* Periodically send the logs (after hitting a certain buffer size or time - whichever comes first so say every 30 seconds or when the buffer reaches 1MiB in size)
* Minimize footprint (memory mostly) - seems pretty ok already
* Minimize storage - currently the binary is 26MB. Wondering if we can reduce that

Is there a safer way to tell journalbeat to send everything from this boot (at start-up and everything that comes in from then)? Setting the queue_size this high might still not be enough in exceptional cases and might do things with the memory requirements that might be painful.

Any other suggestions are more than welcome as well :)

TIA
