### ISSUE TITLE
Nested configuration

### ISSUE THREAD

**Issue by kinghrothgar** [mheese/journalbeat#14]
Before I did the work I was wondering if you liked this change to config.  While I was working on a different pull request I thought it might make sense especially as more options an features are added:

```yaml
shipper:
  name: journalbeat
  #tags: [ "blue", "red" ]
input:
  # What position in journald to seek to at start up
  # options: cursor, tail, head (defaults to tail)
  seek_position: cursor

  cursor:
    write_state: true
    state_file: /tmp/journalbeat-cursor-state
    flush_secs: 3
    # If seek_position is set to cursor and seeking to cursor fails
    # fall back to this method.  If set to none will it will exit
    # options: tail, head, none (defaults to tail)
    seek_fallback: tail

  parsing:
    clean_field_names: true
    convert_to_numbers: false
    move_metadata_to_field: journal
  #fields_dest: my.nested.destination
  #fields:
  #  custom_field: custom_value
  #  sub:
  #    nested: field
output:
  console:
    pretty: true
  #logstash:
  #  hosts: ["localhost:5044"]
```

I'll implement it if you like it.  I haven't wrapped my head around the fields_dest and fields options yet so I wasn't sure what to do with them.
