### ISSUE TITLE
Logs missing

### ISSUE THREAD

**Issue by pallix** [mheese/journalbeat#154]
I am using version 5.6.9. I publish events with the following script:

```
#!/bin/bash

i=0
while true; do
    echo $i
    echo $i | systemd-cat
    sleep 3
    i=$((i+1))
done
```

and have the following configuration:

```

journalbeat:
  # What position in journald to seek to at start up
  # options: cursor, tail, head (defaults to tail)
  seek_position: cursor

  # If seek_position is set to cursor and seeking to cursor fails
  # fall back to this method.  If set to none will it will exit
  # options: tail, head, none (defaults to tail)
  # cursor_seek_fallback: none

  # Store the cursor of the successfully published events
  # write_cursor_state: true
[...]
output.console:
  # Boolean flag to enable or disable the output module.
  enabled: true

```

After less than ten events, I can see that some events are not printed in the console as expected.

Is this a bug or am I doing something wrong?
