### ISSUE TITLE
Can not forward journald logs to logstash using docker

### ISSUE THREAD

**Issue by karamen1** [mheese/journalbeat#156]
Dear journalbeat teams,

here is my docker-compose file
```
version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-config:/usr/share/elasticsearch/config/
      - elasticsearch-data:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == monitor

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.2
    ports:
      - 5000:5000/tcp
      - 5044:5044
      - 9600:9600
    volumes:
      - logstash-p:/usr/share/logstash/pipeline/
      - logstash-config:/usr/share/logstash/config/
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.type == monitor

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - kibana:/usr/share/kibana/config
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.type == monitor

  journalbeat:
    image: mheese/journalbeat
    depends_on:
      - elasticsearch
    environment:
      LOGSTASH_HOST: logstash:5044
    volumes:
      - /var/log/journal:/var/log/journal
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.type == app

volumes:
  elasticsearch-config:
  elasticsearch-data:
  logstash-p:
  logstash-config:
  kibana:
```

when i run this, here is journalbeat logs
`beat.go:283: INFO Home path: [/] Config path: [/] Data path: [//data] Logs path: [//logs]
beat.go:186: INFO Setup Beat: journalbeat; Version: 5.5.2
logstash.go:90: INFO Max Retries set to: 3
outputs.go:108: INFO Activated logstash as output plugin.
publish.go:295: INFO Publisher name: journalbeat
metrics.go:23: INFO Metrics logging every 30s
async.go:63: INFO Flush Interval set to: 1s
async.go:64: INFO Max Bulk Size set to: 2048
journalbeat.go:95: WARN Could not seek to cursor: reading cursor state file failed: open /data/journalbeat-cursor-state: no such file or directory
journalbeat.go:52: INFO Seek to tail successful
beat.go:221: INFO journalbeat start running.
journalbeat.go:185: INFO Journalbeat is running!
journalbeat.go:203: WARN could not read the pending queue: open /.journalbeat-pending-queue: no such file or directory
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
metrics.go:34: INFO No non-zero metrics in the last 30s
`

Would you check for me where is lacking.
i sure config journald log to /var/log/jounald folder
Thanks
