### ISSUE TITLE
Journalbeat WARN message loop "Received unknown error when reading a new entry: failed to read message field: 74, cursor read error: failed to get cursor: 74"

### ISSUE THREAD

**Issue by jasonswat** [mheese/journalbeat#159]
We were able to reproduce the issue by: 
1. Stopping the endpoint that journalbeat writes to (elasticsearch in our case).
2. Wait for logs in /var/log/journal/ to roll over. We set these setting in /etc/systemd/journald.conf to reproduce the issue faster
```
RateLimitIntervalSec=0s
RateLimitBurst=0
RuntimeMaxFileSize=1
RuntimeMaxFiles=5
```
3. Start journalbeat endpoint again so it can continue to send logs (elasticsearch)
4. Once it connects to the endpoint, `journalctl -fu journalbeat` will get into a loop and send this message over and over:
```
Jan 23 22:22:40 ip-172-19-67-44.us-west-2.compute.internal docker[21430]: 2019/01/23 22:22:40.432486 follow.go:65: WARN Received unknown error when reading a new entry: failed to read message field: 74, cursor read error: failed to get cursor: 74
Jan 23 22:22:40 ip-172-19-67-44.us-west-2.compute.internal docker[21430]: 2019/01/23 22:22:40.564450 follow.go:65: WARN Received unknown error when reading a new entry: failed to read message field: 74, cursor read error: failed to get cursor: 74
```

This ended up filling up disk in /var/lib/docker/ because of all the messages

Could this be changed to reset the cursor or exit when it fails?

docker startup configuration
```
ExecStart=/usr/bin/docker run --rm \
  --name=journalbeat \
  --hostname="${COREOS_PRIVATE_IPV4}" \
  --env-file /etc/environment \
  -v /etc/journalbeat:/etc/journalbeat \
  -v /var/log/journal:/var/log/journal \
  -v /run/log/journal:/run/log/journal \
  -v /etc/machine-id:/etc/machine-id:ro \
  --tmpfs=/data:rw,noexec,nosuid,size=32k \
  mheese/journalbeat:latest \
    /journalbeat -e -c /etc/journalbeat/journalbeat.yml
```
journalbeat.yml settings:
```
journalbeat:
  seek_position: cursor
  cursor_seek_fallback: tail
  write_cursor_state: true
  cursor_state_file: /data/journalbeat-cursor-state
  cursor_flush_period: 5s
  clean_field_names: true
  convert_to_numbers: false
  move_metadata_to_field: journal
  units:
  - "elasticsearch.service"
  - "logstash.service"
```

CoreOS version:
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1855.4.0
DISTRIB_CODENAME="Rhyolite"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1855.4.0 (Rhyolite)"

journalbeat docker version (pulling from mheese/journalbeat:latest)
journalbeat version 5.5.2 (amd64), libbeat 5.5.2

Let me know if I can provide any more files or info to reproduce the issue
