### ISSUE TITLE
Adding fields, tags?

### ISSUE THREAD

**Issue by arwineap** [mheese/journalbeat#31]
It looks like journalbeat at one point supported fields:
https://github.com/mheese/journalbeat/commit/04ae580cd17080290bb51da730bfa55074cc465c

I do see that journalbeat may support "tags":
https://github.com/mheese/journalbeat/blob/master/etc/journalbeat.yml#L2

But it seems like tags do not support key value pairs like I would expect

Is there anyway to replicate the fields functionality from filebeat?
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#configuration-fields

**Comment by nicorevin** [comment]
Fields and fields_under_root are libbeat features. Hence they are fully supported by journalbeat. Only the input section is specific for JB.
Everything else can be taken from here - https://github.com/elastic/beats/blob/c4beed08da4de2da8cb6fa00a97f81a2f564ee8c/libbeat/_meta/config.full.yml

**Comment by arwineap** [comment]
Thanks, that worked perfectly!

For the googlers, I just put it outside of the input stanza like this:
```
fields:
  foo: bar
  fizz: buzz

input:
  # What position in journald to seek to at start up
  # options: cursor, tail, head (defaults to tail)
  seek_position: cursor
```
