### ISSUE TITLE
Investigate creating a docker image for mesos + consul + marathon

### ISSUE THREAD

**Issue by mbrooks** [mheese/journalbeat#55]
As servers are spun up and down in mesos, they typically are moved around to where they get new IP addresses, etc. Therefor it is not ideal to set a server at startup because the server locations are guaranteed to change. Consul allows an image to grab the current list of servers in a relatively healthy way. This task is to investigate creating a docker image specifically for the mesos + consul + marathon environment.

Some of the questions we need to answer:
* Should we support service discovery using consul? Is there a consistent setup that works for majority of systems running mesos and/or consul?
* Would a custom image off our our main docker release be good enough?
* Should we create a separate build and tag for this? I.E. `VERSION-mesos`

 Example Mesos + consul + marathon config:
```
{{/* begin lookup prep*/}}
{{ $requiredTags :=  "prod,beats" | split "," | toJSON | parseJSON }}
{{ $lookup := service "TAGNAME.LOGSTASH-SERVICE-NAME-HERE|any" }}
{{/* This oddity is here to ensure that the scratchMap "targets" gets created *with the correct type*. Thanks, HashiCorp. */}}
{{ define "first" }}{{range $i, $v := .}}{{if eq $i 0}}{{$v.Node}}:{{$v.Port}}{{end}}{{end}}{{end}}
{{ scratch.MapSet "targets" (executeTemplate "first" $lookup) "unset" }}
{{ range $s := $lookup}}{{ if containsAll $requiredTags .Tags}}{{scratch.MapSet "targets" (print $s.Node ":" $s.Port) (print $s.Address ":" $s.Port) }}{{end}}{{end}}
{{/* end lookup */}}
journalbeat:
  seek_position: cursor
  cursor_seek_fallback: head
  write_cursor_state: true
  cursor_state_file: /journalbeat/journalbeat-cursor-state
  clean_field_names: true
name: journalbeat
processors:
    - add_cloud_metadata:
output.elasticsearch:
  enabled: false
output.logstash:
    max_retries: 1
    enabled: true
    hosts: {{ scratch.MapValues "targets" | toJSON }}
    worker: 1
    compression_level: 3
    timeout: 2
logging.metrics.enabled: true
logging.to_files: false
```

@kainz was the original requestor for this functionality.
