### ISSUE TITLE
Type derived from the system journal

### ISSUE THREAD

**Issue by johnmarcou** [mheese/journalbeat#75]
Hi,

I added this code to be able to set the document type from the source logger process.
The file is `beater/journalbeat.go`:
```
...
// TODO: type and input_type should be derived from the system journal
_, ok := event["type"].(string)
if !ok {
    event["type"] = jb.config.DefaultType
...
```

Could you please add this `type` override feature ?

_Use case for instance:_

In our case, the process is a Python app which prints its log in JSON format, with a `type` field, to STDOUT in a docker container, then the docker deamon is set to forward container logs to journald.

And when the `pipeline` field is set, journalbeat use it to send the doc to the right ingest pipeline.
```
  pipelines:
    - pipeline: "%{[pipeline]}"
      when.not.equals:
        pipeline: ""
    - pipeline: "docker_log"
      when.regexp:
        container_name: ".+"
    - pipeline: "journalbeat"
```
Finally, we can control from the app or the container configuration the document type and its ingest pipeline. This is important when you use index template in ES, to match the right type/mapping fields.
