### ISSUE TITLE
Support JSON formatted messages

### ISSUE THREAD

**Issue by BernhardBerbuir** [mheese/journalbeat#82]
Currently field __MESSAGE__ is treated as string. Therefore, a JSON formatted message is not processed properly by logstash. It would be nice to be able to use JSON formatted message like it is supported by filebeat (see 
[filebeat config-json](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-filebeat-options.html#config-json))

**Comment by nicorevin** [comment]
Hi!

You need to define a processor for that in your config file like here https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html

See also #69

**Comment by stvnwrgs** [comment]
@nicorevin Your suggestion is not working for me. 

I'm using the newest journalbeat version and added 

```
processors:
  - decode_json_fields:
    fields: ["message"]
    process_array: false
    max_depth: 1
    target: ""
    overwrite_keys: true
```

To my config but the application just crashes without any error message. Actually, there is not log message at all when startin journalbeat with a corrupted config.
