### ISSUE TITLE
Running on kubernetes

### ISSUE THREAD

**Issue by SleepyBrett** [mheese/journalbeat#84]
Having trouble spinning this up in a pod and I think I've tracked down the issue.

I'm using the following template (eventually a daemonset, but for now just testing with 1 replica)

````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: journalbeat
  namespace: utils
  labels:
    app: journalbeat
spec:
  replicas: 1
  template:
    metadata:
      name: journalbeat
      labels:
        app: journalbeat
      annotations:
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      tolerations:
      - operator: "Exists"
      securityContext: {fsGroup: 0, runAsUser: 0}
      terminationGracePeriodSeconds: 20
      containers:
      - name: journalbeat
        image: quay.io/nordstrom/journalbeat:v5.5.0
        command: 
          - /journalbeat
        args:
          - -e
          - -c
          - /config/journalbeat.yml
        env:
        - name: KAFKA_BOOTSTRAP_ADDR
          value: "xxxxxxx:9092"
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: var-log-journal
          mountPath: /var/log/journal
        - name: run-log-journal
          mountPath: /run/log/journal
        # - name: etc-machineid
        #   mountPath: /etc/machine-id
        - name: journalbeat-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: journalbeat-config
        configMap:
          name: journalbeat-config
      - name: var-log-journal
        hostPath:
          path: /var/log/journal
      - name: run-log-journal
        hostPath:
          path: /run/log/journal
      # - name: etc-machineid
      #   hostPath:
      #     path: /etc/machine-id
````

The problem is that kubernetes cannot mount just a single file in a path (at least in 1.6.x which is what we are on currently). This means the machine-id file is wrong.

In the container:
````
root@journalbeat-4197287578-vc7fr:/var/log/journal# cat /etc/machine-id
5d12f049cbc39eb705e94d4b4fe4e580
root@journalbeat-4197287578-vc7fr:/var/log/journal# ls /var/log/journal
2ccec43a276446f7ac3089f1c9767e4b  remote
````
On the host which the pod is running:
````
core@ip-172-16-202-62 /var/log/journal $ cat /etc/machine-id
2ccec43a276446f7ac3089f1c9767e4b
core@ip-172-16-202-62 /var/log/journal $ ls /var/log/journal/
2ccec43a276446f7ac3089f1c9767e4b  remote
````

I assume the sdjournal library, looks at /etc/machine-id and then tries to open the files in /var/log/journal/(machine-id)/.

So I can certainly hack this with an entrypoint script, mount the hosts `/etc/machine-id` to some random path, use the script to move the machine-id to /etc/ myself. This, however, is ugly and a little fragile. 

Thoughts without digging into the sdjournal package, is it possible to change the pointer to the /etc/machine-id file through env variable or commandline flag?

**Comment by nicorevin** [comment]
I've just tried to reproduce in minikube with a simple image:
```yaml
    spec:
      volumes:
      - hostPath:
          path: /var/log/vmware-vmsvc.log
        name: logfile
      containers:
        volumeMounts:
        - mountPath: /var/log/vmware-vmsvc.log
          name: logfile
          readOnly: true
```
running on minikube
I see `/var/log/vmware-vmsvc.log` and it is the same as on host.
