### ISSUE TITLE
journalbeat eats lots of memory occasionally

### ISSUE THREAD

**Issue by bergerx** [mheese/journalbeat#88]
We use journalbeat to push all systemd logs to a kafka topic. Our journalbeat version is `journalbeat version 5.1.1 (amd64), libbeat 5.1.1` running on `CentOS Linux release 7.3.1611 (Core)`.

I see many nodes are consuming memory more than 1G, and they are up for a week.

![image](https://user-images.githubusercontent.com/45531/28519960-4f714ec6-7076-11e7-9cd2-eca0019257e9.png)

Here  is an example config from our prod:
```yaml
journalbeat:
  seek_position: cursor
name: journalbeat
output.kafka:
  enabled: true
  hosts: ["broker.confluent-elk.l4lb.thisdcos.directory:9092"]
  topic: 'journalbeat'
  required_acks: 1
  max_message_bytes: 1000000
logging.to_files: true
logging.files:
  path: /var/log/journalbeat
  name: journalbeat
```
