### ISSUE TITLE
Docker not producing any logs

### ISSUE THREAD

**Issue by vishr** [mheese/journalbeat#93]
Hi,

I am running journalbeat docker on ubuntu 17.04 but I don't see any logs in the console or logstash, however, `journalctl -f` do produce them on the host. Any ideas?

```sh
$ docker run -d -v /var/log/journal:/var/log/journal \
-v /run/log/journal:/run/log/journal \
-v /etc/machine-id:/etc/machine-id \
my-journalbeat
```

Dockerfile

```Dockerfile
FROM mheese/journalbeat

COPY journalbeat.yml .

CMD ["./journalbeat", "-e", "-c", "journalbeat.yml"]
```

Config

```yaml
journalbeat:
  seek_position: cursor
  cursor_seek_fallback: tail
  write_cursor_state: true
  cursor_state_file: /data/cursor
  pending_queue.file: /data/pending
  move_metadata_to_field: journal

# output.logstash:
#   enabled: true
#   hosts: ["logstash:5044"]

output.console:
  enabled: true
  pretty: false

logging.to_files: false
```
